//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFLocalization.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XFLocalization.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Doggy Digital Creative Inc. 的當地語系化字串。
        /// </summary>
        internal static string 多奇數位創意有限公司 {
            get {
                return ResourceManager.GetString("多奇數位創意有限公司", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password 的當地語系化字串。
        /// </summary>
        internal static string 密碼 {
            get {
                return ResourceManager.GetString("密碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Account 的當地語系化字串。
        /// </summary>
        internal static string 帳號 {
            get {
                return ResourceManager.GetString("帳號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login 的當地語系化字串。
        /// </summary>
        internal static string 登入 {
            get {
                return ResourceManager.GetString("登入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your Email 的當地語系化字串。
        /// </summary>
        internal static string 請輸入您的電子郵件信箱 {
            get {
                return ResourceManager.GetString("請輸入您的電子郵件信箱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your password 的當地語系化字串。
        /// </summary>
        internal static string 請輸入該帳號使用的密碼 {
            get {
                return ResourceManager.GetString("請輸入該帳號使用的密碼", resourceCulture);
            }
        }
    }
}
